name: Build Wingman Android APK

env:
  main_project_module: app
  playstore_name: Wingman

on:
  push:
    branches: [ feature/android-native-app, main, master ]
  pull_request:
    branches: [ feature/android-native-app, main, master ]
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set current date
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug --stacktrace

      - name: Build release APK
        run: cd android && ./gradlew assembleRelease --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - Wingman-Android-Debug-APK
          path: android/app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - Wingman-Android-Release-APK
          path: android/app/build/outputs/apk/release/*.apk
